spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
        default_schema:
        jdbc:
          time
  data:
    redis:
      port: 6379
      host: redis
      password:


aws:
  s3:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080
  tomcat:
    connection-timeout: 180000
    max-http-response-header-size: 30MB
    keep-alive-timeout: 180000
  max-http-request-header-size: 30MB
ai-server:
  url: "http://rag_server:8000/ai-answer"