spring:
  application:
    name: capstone2
  profiles:
    active: proc
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8090
