spring:
  application:
    name: capstone2
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG


aws:
  s3:
    credentials:
      accessKey: ***REMOVED***
      secretKey: ***REMOVED***
      region: ***REMOVED***
    bucket: ***REMOVED***

jwt:
  secret: ***REMOVED***

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  show-login-endpoint: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
  tomcat:
    connection-timeout: 180000
    max-http-response-header-size: 16KB
  max-http-request-header-size: 16KB
  ssl:
    enabled: false