name: CICD
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
#      - name: Docker Compose Start
#        run: |
#         docker-compose start | true
      - name: Print Spring Profile
        run: |
          echo "Active profile: ${{ env.SPRING_PROFILES_ACTIVE}}"
        env:
          SPRING_PROFILES_ACTIVE: prod

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -Dspring.profiles.active=prod

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Docker version
        run: |
          docker --version
          
      - name: Stop existing application
        run: |
          docker ps -q --filter "name=capstone2" | xargs -r docker stop
          docker ps -aq --filter "name=capstone2" | xargs -r docker rm

      - name: Remove old Docker image
        run: |
          docker rmi capstone2:latest || true  # 이미지가 없을 경우 오류를 무시
          
      - name: Build Docker image
        run: |
          docker build -t capstone2:latest .

      - name: Run Docker container
        run: |
          docker run -d --restart=always --network host --name capstone2 -p 80:8080 -e ACTIVE_PROFILE=prod capstone2:latest
          
      - name: Check Docker network
        run: |
          docker network inspect llm-network

      - name: Check application logs
        run: |
          docker logs capstone2